// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"my_assistant_go/app/model/internal"
)

// ConfigType is the golang structure for table config_type.
type ConfigType internal.ConfigType

// Fill with you ideas below.
