// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// ConfigType is the golang structure for table config_type.
type ConfigType struct {
	Id       int    `orm:"id,primary" json:"id"`       //
	TypeName string `orm:"type_name"  json:"typeName"` //
	Comment  string `orm:"comment"    json:"comment"`  // 说明
}
